<?php

declare(strict_types=1);

use Maho\Config\Route;
use Maho\Security\RateLimitScope;

/**
 * AJAX endpoints for the XPay Build embedded checkout.
 *
 * Two endpoints:
 *  - getPaymentData: lightweight init endpoint returning the SDK config
 *    (alias, MAC, codTrans, saved cards) needed to mount the hosted fields.
 *  - placeOrder: terminal endpoint that receives the nonce generated by the
 *    XPay SDK on the frontend, authorizes it and places the order.
 *
 * SPDX-FileCopyrightText: Tony <https://github.com/empiricompany>
 * SPDX-License-Identifier: OSL-3.0
 * @package Nexi_XPayBuild
 */
class Nexi_XPayBuild_CheckoutController extends Mage_Core_Controller_Front_Action
{
    private const RATE_LIMIT_ATTEMPTS = 30;
    private const RATE_LIMIT_WINDOW = 300;

    /**
     * Parse JSON request body params into the request object
     */
    #[\Override]
    public function preDispatch(): static
    {
        parent::preDispatch();

        $contentType = $this->getRequest()->getHeader('Content-Type');
        if ($contentType && str_contains($contentType, 'application/json')) {
            $body = $this->getRequest()->getRawBody();
            if ($body) {
                $data = Mage::helper('core')->jsonDecode($body);
                if (is_array($data)) {
                    $allowed = ['form_key', 'save_card', 'saved_card_id', 'xpay_nonce', 'xpay_cod_trans'];
                    $this->getRequest()->setParams(array_intersect_key($data, array_flip($allowed)));
                }
            }
        }

        return $this;
    }

    #[Route('/nexixpaybuild/checkout/getPaymentData', methods: ['POST'])]
    public function getPaymentDataAction(): void
    {
        $result = ['success' => false];

        try {
            $this->_checkRateLimit('nexi_xpaybuild_payment_data');

            if (!$this->_validateFormKey()) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Invalid form key.'));
            }

            $quote = Mage::getSingleton('checkout/session')->getQuote();
            if (!$quote->getId() || !$quote->getItemsCount()) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Cart is empty.'));
            }

            $helper = Mage::helper('nexi_xpaybuild');
            $alias = $helper->getXpayAlias();
            $macKey = $helper->getXpayMacKey();

            if (!$alias || !$macKey) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Nexi XPay is not configured.'));
            }

            $currencyCode = $quote->getQuoteCurrencyCode();
            $importo = $helper->formatAmountToMinorUnit($quote->getGrandTotal(), $currencyCode);
            $divisa = $helper->getCurrencyNumericCode($currencyCode);
            $codTrans = $helper->generateTransactionId($quote);
            $timeStamp = (string) (time() * 1000);
            $mac = Mage::helper('nexi_xpaybuild/mac')->calculateInitMac($codTrans, $divisa, $importo, $macKey);

            $data = [
                'alias' => $alias,
                'importo' => $importo,
                'codTrans' => $codTrans,
                'divisa' => $divisa,
                'timeStamp' => $timeStamp,
                'mac' => $mac,
                'sdkUrl' => $helper->getXpaySdkUrl(),
                'environment' => $helper->getXpayEnvironment(),
                'language' => 'ITA',
                'cardFormStyle' => $helper->getCardFormStyle(),
            ];

            $customerSession = Mage::getSingleton('customer/session');
            if ($customerSession->isLoggedIn() && $helper->getOneclickEnabled()) {
                $customerId = (int) $customerSession->getCustomerId();
                $savedCards = Mage::helper('nexi_xpaybuild/savedCard')->getActiveCards($customerId, 'XPAY');
                $contractsData = [];
                $idx = 0;
                foreach ($savedCards as $card) {
                    $cardCodTrans = substr($card->getId() . '-' . time() . '-' . $idx, 0, 30);
                    $idx++;
                    $cardTs = (string) (time() * 1000);
                    $cardMac = Mage::helper('nexi_xpaybuild/mac')->calculateInitMac($cardCodTrans, $divisa, $importo, $macKey);
                    $contractsData[] = [
                        'cardId' => $card->getId(),
                        'maskedPan' => $card->getMaskedPan(),
                        'brand' => $card->getBrand(),
                        'expiryMonth' => $card->getExpiryMonth(),
                        'expiryYear' => $card->getExpiryYear(),
                        'gatewayToken' => $card->getGatewayToken(),
                        'codTrans' => $cardCodTrans,
                        'timeStamp' => $cardTs,
                        'mac' => $cardMac,
                    ];
                }
                $data['savedCards'] = $contractsData;
            }

            $result['success'] = true;
            $result['data'] = $data;
        } catch (\Throwable $e) {
            $result['message'] = $e->getMessage();
            Mage::logException($e);
        }

        $this->getResponse()->setHeader('Content-Type', 'application/json');
        $this->getResponse()->setBody(Mage::helper('core')->jsonEncode($result));
    }

    /**
     * Save the nonce and payment data on the quote payment, then delegate to
     * the framework's saveOrder() which creates the DB transaction and calls
     * authorize()/capture() inside it. If the gateway fails → rollback → no
     * orphan payment.
     */
    #[Route('/nexixpaybuild/checkout/placeOrder', methods: ['POST'])]
    public function placeOrderAction(): void
    {
        $result = ['success' => false];

        try {
            $this->_checkRateLimit('nexi_xpaybuild_place_order');

            if (!$this->_validateFormKey()) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Invalid form key.'));
            }

            $quote = Mage::getSingleton('checkout/session')->getQuote();
            if (!$quote->getIsActive()) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('This order has already been placed.'));
            }

            $nonce = preg_replace('/[^a-zA-Z0-9\-_]/', '', (string) $this->getRequest()->getParam('xpay_nonce', ''));
            $codTrans = preg_replace('/[^a-zA-Z0-9\-]/', '', (string) $this->getRequest()->getParam('xpay_cod_trans', ''));
            $savedCardId = (int) $this->getRequest()->getParam('saved_card_id', 0);
            $saveCard = (bool) $this->getRequest()->getParam('save_card', false);

            if ($nonce === '' || strlen($nonce) > 256) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Payment nonce is missing. Please retry.'));
            }

            if ($codTrans === '' || strlen($codTrans) > 30) {
                Mage::throwException(Mage::helper('nexi_xpaybuild')->__('Invalid payment data.'));
            }

            $payment = $quote->getPayment();
            $payment->setMethod('nexi_xpaybuild');
            $payment->setAdditionalInformation('nexi_nonce', $nonce);
            $payment->setAdditionalInformation('nexi_cod_trans', $codTrans);
            $payment->setAdditionalInformation('nexi_gateway', 'XPAY');
            $payment->setAdditionalInformation('nexi_saved_card_id', $savedCardId);
            $payment->setAdditionalInformation('nexi_save_card', $saveCard);

            $quote->collectTotals();
            Mage::getModel('sales/service_quote', $quote)->validate();

            try {
                $onepage = Mage::getSingleton('checkout/type_onepage');
                $onepage->setQuote($quote);
                $onepage->saveOrder();
            } catch (\Throwable $e) {
                Mage::helper('nexi_xpaybuild')->log(
                    sprintf('CRITICAL: Nexi payment authorized (codTrans %s) but order placement failed: %s', $codTrans, $e->getMessage()),
                    \Monolog\Level::Error,
                );
                throw $e;
            }

            $quote->setIsActive(0);
            $quote->save();

            $result['success'] = true;
            $result['redirect_url'] = Mage::getUrl('checkout/onepage/success', ['_secure' => true]);
        } catch (\Throwable $e) {
            $result['message'] = $e->getMessage();
            Mage::logException($e);
        }

        $this->getResponse()->setHeader('Content-Type', 'application/json');
        $this->getResponse()->setBody(Mage::helper('core')->jsonEncode($result));
    }

    /**
     * Session-scoped rate limiting for the public checkout endpoints.
     *
     * @throws Mage_Core_Exception When the limit is exceeded.
     */
    protected function _checkRateLimit(string $namespace): void
    {
        $limiter = Mage::helper('core')->rateLimiter(
            $namespace,
            self::RATE_LIMIT_ATTEMPTS,
            self::RATE_LIMIT_WINDOW,
            RateLimitScope::Session,
        );

        if (!$limiter->attempt()) {
            Mage::throwException(
                Mage::helper('nexi_xpaybuild')->__('Too many requests. Please wait a moment and try again.'),
            );
        }
    }
}
